### ISSUE TITLE
Armours using this library show as error cubes on cosmetic Armor Mod

### ISSUE THREAD

**Issue by MeatVegetalbe** [AzureDoom/AzureLib-Armor#1]
I found that armours using this library show as an pink error cube when trying to place them in the cosmetic slot in [Cosmetic Armor Mod](https://modrinth.com/mod/cosmetic-armor), not sure what could be causing the conflict, however I figured I should report it to the two of you.

**Comment by AzureDoom** [comment]
What version and mods are used? Likely, they are not taking into account for armors using non-vanilla rendering/custom rendering.

**Comment by MeatVegetalbe** [comment]
I am using 1.20.1 Mincecraft, azurelib 2.0.0, and cosmetic armor 1.6.0

**Comment by AzureDoom** [comment]
Azurelib doesn't provide any built-in armors.

**Comment by MeatVegetalbe** [comment]
Oh sorry, I originally found the issue on [wizards-1.0.4+1.20.1.jar](https://modrinth.com/mod/wizards) however other mods using this library also show the same issue. I notified the Wizards creator and they attempted to fiddle with it, and think it is something to do with either the library, or an issue with cosmetic armor.

**Comment by AzureDoom** [comment]
This would be on Cometic Armor, most likely using https://github.com/apace100/cosmetic-armor/blob/1.20/src/main/java/io/github/apace100/cosmetic_armor/mixin/MixinCosmeticArmorVisibility.java#L87-L88C43 to be exact. They need to update to use Mixin Extras WrapOperation https://github.com/LlamaLad7/MixinExtras/wiki/WrapOperation

**Comment by MeatVegetalbe** [comment]
Thanks, you're awesome

**Comment by AzureDoom** [comment]
After checking, that seems to solve any possible crashes. Sadly they would need to rewrite their mixins for this, as it only either does it's custom rendering or vanillas. No support for 3rd party rendering.
