### ISSUE TITLE
Crash when shot by a skeleton

### ISSUE THREAD

**Issue by leftbones** [AzureDoom/AzureLib-Armor#11]
A player on my server had a random crash while being shot by a skeleton, here's his crash log: https://mclo.gs/hUkjSka

One thing to note is we've all been playing on the server for a few days and this is the first time this has happened, so it's not consistent. I'm not great at reading these logs, but from what I could gather it seems to be an issue with AzureLib Armor. If I'm wrong, please let me know!

**Comment by AzureDoom** [comment]
This isn't an issue on the AzureLib Armor side; this would be Iris; please ensure you are using the latest version of it there, as this should have been fixed on their end.
