### ISSUE TITLE
AzureLib-Armor causes Minecraft 1.21 to get stuck at the end of the loading screen, causing game to not boot.

### ISSUE THREAD

**Issue by MylesGit** [AzureDoom/AzureLib-Armor#14]
AzureLib Armor 2.3.2
Fabric Loader 0.16.5
Minecraft 1.21

This is probably a mod incompatibility of some sort. I will try to look into it further, wondering if anyone has any input.
I am not a version behind as 2.3.2 is the latest compatible version for Minecraft 1.21 as all higher versions require 1.21.1

Logs Below
https://mclo.gs/SKuDyIn

Screenshot Below
![image](https://github.com/user-attachments/assets/d21c8936-a045-4aa2-a694-cd2dd7b1ae88)

**Comment by AzureDoom** [comment]
Don't use 1.21.0, use 1.21.1, not support will be fixing for 1.21.0
