### ISSUE TITLE
[CRASH ON STARTUP] [1.21.1] NeoForge 21.1.61 + Azure Lib Armor 2.3.13

### ISSUE THREAD

**Issue by Tapacywka** [AzureDoom/AzureLib-Armor#15]
**Minecraft Info:**
Minecraft Version: 1.21.1
Modloader version: NeoForge 21.1.61
Mod version: 2.3.13

**Describe the bug:**
Unable to start the game, it either crashes on startup or gets stuck on the loading screen.

**Steps to reproduce the behavior:**
1. Create a clean instance of 1.21.1 NeoForge 21.1.61.
2. Install Azure Lib Armor 2.3.13 for NeoForge.
3. Start the game.
4. See error.

**Screenshots:**
![image](https://github.com/user-attachments/assets/69e7034d-a3f1-4b1a-a361-a1e9c9e8bef4)

**Logs:**
https://mclo.gs/ym2MwwZ

**Comment by AzureDoom** [comment]
Because its made for .62+.

**Comment by Tapacywka** [comment]
> Because its made for .62+.

And which version supports .61?

**Comment by HertzX777** [comment]
> > Porque é feito para .62+.
> 
> E qual versão suporta .61?

Hi friend, I know it's been a while, but have you found any solution?

**Comment by Tapacywka** [comment]
> > > Porque é feito para .62+.
> > 
> > 
> > E qual versão suporta .61?
> 
> Hi friend, I know it's been a while, but have you found any solution?

Update your NeoForge Loader and AzureArmor Lib to the latest versions.
