### ISSUE TITLE
Don't use 1.21.0, use 1.21.1, not support will be fixing for 1.21.0

### ISSUE THREAD

**Issue by Irving240177** [AzureDoom/AzureLib-Armor#17]
Don't use 1.21.0, use 1.21.1, not support will be fixing for 1.21.0

_Originally posted by @AzureDoom in https://github.com/AzureDoom/AzureLib-Armor/issues/14#issuecomment-2347316716_
  

Is there something that the users of 1.20 can we do?, right now i can't change mi version to 1.21.1, I have the same problem in the loading screen.

**Comment by AzureDoom** [comment]
No, this is due to neoforge changes that only apply to 1.21.1+
