### ISSUE TITLE
Incompatibility with world and resource reloading with Entity Texture Features

### ISSUE THREAD

**Issue by Ampflower** [AzureDoom/AzureLib-Armor#5]
## Steps to reproduce
1. Install
   - Minecraft 1.20.1
   - Fabric or Quilt
   - AzureLib Armor 2.0.3
   - Wizards 1.0.4+1.20.1 or Paladins 1.0.4+1.20.1
   - Entity Texture Features 5.1.2 or 5.0
2. Load into world
3. Put wizard or crusader armour on an armour stand or other living entity
4. Reload
   - The world
   - A resource pack
   - The entire resource system (F3+T)

## Logs

[A lot of crashlog.log](https://github.com/AzureDoom/AzureLib-Armor/files/13838520/A.lot.of.crashlog.log)

**Comment by AzureDoom** [comment]
This is something on their end breaking with the custom texture support we have here: https://github.com/AzureDoom/AzureLib-Armor/tree/1.20.1/common/src/main/java/mod/azure/azurelibarmor/cache/texture as these are working as intended and using the proper systems, this will require a fix from Entity Textures Features for this.
