### ISSUE TITLE
Crash while trying to put Priest & Paladin armor on (using Sinytra connector mod)

### ISSUE THREAD

**Issue by vivagabe** [AzureDoom/AzureLib-Armor#6]
Hopefully an easy fix.

[crash-2024-03-24_22.33.32-client.txt](https://github.com/AzureDoom/AzureLib-Armor/files/14753928/crash-2024-03-24_22.33.32-client.txt)

**Comment by AzureDoom** [comment]
Looks like something is breaking the assets lookup. Please test with just Priest and Paladin with Sintyra standalone. I suggest immediatelyfast myself.

**Comment by vivagabe** [comment]
I removed immediately fast but still crashed. I did some testing and it looks like Blueprint 7.02 by team abnormal is causing the issue. Is there anything u can do or should I inform them to have them resolve the issue?

**Comment by AzureDoom** [comment]
Is it reproducible with just that mod and the mods for Priest and Paladin?

**Comment by vivagabe** [comment]
No issues with just those mods. I only have issues when Blueprint 7.02 is installed.

**Comment by vivagabe** [comment]
Connector Sinytra updated today and has resolved the issue. thanks!
