### ISSUE TITLE
Incompatibility with ledgendary tooltips

### ISSUE THREAD

**Issue by PolyframeX** [AzureDoom/AzureLib-Armor#7]
When playing with AzureLib Armor, the armor will render improperly on ledgendary tooltips.

![image](https://github.com/AzureDoom/AzureLib-Armor/assets/80133652/153f77d9-9b5c-4f4b-86f9-7185ca1df245)

Minecraft: 1.20.1
Fabric Loader: 0.15.11
FAPI: 0.92.1
Wizards: 1.2.0
Ledgendary Tooltips: 1.4.5

**Comment by AzureDoom** [comment]
This an issue on Tool tips side, as I've worked with them on this. Enchant the armor and you'll see it works correctly. It's an issue in it's render code.
