### ISSUE TITLE
Incompability with Cosmetic Armor Fabric mod

### ISSUE THREAD

**Issue by s-element** [AzureDoom/AzureLib-Armor#8]
There is an issue when I try to put armor from the AzureLib on the layer where the cosmetic armor is placed, a black box appears instead of a body part, which breaks the visual component. 

![image](https://github.com/ZsoltMolnarrr/Archers/assets/170731140/7f6a2c6b-ee54-4859-805b-28b3cf39facc)
![image](https://github.com/ZsoltMolnarrr/Archers/assets/170731140/0fdae825-a435-4d56-8b60-a9ab408404d8)

Also, when I put the armor under the cosmetic layer, the armor on the cosmetic layer  itself is not displayed.

![image](https://github.com/ZsoltMolnarrr/Archers/assets/170731140/34aef8a5-9c77-4264-b978-6146cf65ce4c)
![image](https://github.com/AzureDoom/AzureLib-Armor/assets/170731140/51bf8305-4924-4cd3-bdf5-f7586cae1c29)

**Comment by AzureDoom** [comment]
https://github.com/apace100/cosmetic-armor/issues/43#issuecomment-1832403182 issue on their side, reported to them already.

**Comment by s-element** [comment]
> [apace100/cosmetic-armor#43 (comment)](https://github.com/apace100/cosmetic-armor/issues/43#issuecomment-1832403182) issue on their side, reported to them already.

Thank you!
